### ISSUE TITLE
Extract participant checklist data

### ISSUE THREAD

**Issue by aridyckovsky** [sokolhessnerlab/itrackvalr#7]
**Problem**

We need a collection of data extracted from CSN checklists.

**Solution**

The following items are requested from the checklists, entered into a CSV with the following requirements:

- The first column has rows for the participant's unique string `id` (i.e., **CSN001**).
- Other columns should values of the set of items in the to-do list:
  - [ ] Session complete (no: 0, yes: 1)
  - [ ] Check distance (mm)
  - [ ] Wears glasses or contacts? (no: 0, yes: 1)
  - [ ] Hits
  - [ ] False Alarms
  - [ ] Bonus ($)
  - [ ] Notes, if substantial

**Comment by aridyckovsky** [comment]
@psokolhessner let me know if you have any feedback on this extraction list.

**Comment by psokolhessner** [comment]
Would it make sense @aridyckovsky to include the recorded validation quality & errors, and revalidation quality & errors? I haven't spot-checked these manually-entered values against the extracted ones - if they're literally the same, then of course we don't need them. 

Could also record experimenter initials?

**Comment by aridyckovsky** [comment]
It looks like the above list does not include **gender** and **age** of participants. Are those in a specific questionnaire? I see them in the `CSN_recruitment` spreadsheet in Drive. @psokolhessner should we add these to the checklist extraction if not elsewhere?

**Comment by psokolhessner** [comment]
@aridyckovsky age & gender were extracted from recruitment information and put in CSVs. The ones on the S drive have age & gender for most participants up through CSN050. I can help finish this if you'd like. Let me know.

**Comment by aridyckovsky** [comment]
@psokolhessner whoops totally missed that CSV. It's not a major priority at the moment to finish that up. I'll add a new issue for this to keep it tracked.

**Comment by psokolhessner** [comment]
Agreed that it's not a major priority (for our purposes, the individual differences in attraction ratings are likely to be more important than reported gender). Thanks @aridyckovsky

**Comment by aridyckovsky** [comment]
Hi @annarini, adding a response here to your questions from the `#studies_csn` channel on Slack.

For reference:

> Hi, when entering the rest of the CSN data, I had a few specific questions on little things, I just didn't want to assume, but are the initials LA and LJA the same? (I added them in the document as they appeared on the scan so LA). There were also some initials that weren't on the github page like AW and EA, but wrote them down as they appeared specifically for CSN 025,028,036. Lastly, for CSN 041 the completion line wasn't filled out the but rest of the data was, so I can assume it was completed but wanted to make sure. Thanks!

Answers:

- The initials for LA and LJA are the same, thanks for catching that! You can also see the [original issue checklist](https://github.com/sokolhessnerlab/itrackvalr/issues/7#issue-835002076), where I've updated the "Experimenter initials" checkbox to reflect the AW initials that were missing before.
- CSN041 _is_ a completed participant, so that's the right call!
